---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-local-storage
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay-manual.local:8443/operators/local-storage/openshift4
    source: registry.redhat.io/openshift4
